# Reference config for ProtoManly's Weather. Copy this file to your instance's
# config/ folder (e.g. instances/BlusteryDay/config/pmweather-server.toml) so the mod uses it.
#Whether tornadoes should be possible
dotornadoes = true
#Whether cyclones should be possible
docyclones = true
#Whether squalls should be possible
dosqualls = true
#Whether radar blocks require a completed WSR-88D to be nearby for display
requirewsr88d = false
#Range within which clouds and storms will spawn from players
# Default: 384
# Range: 256 ~ 2048
spawnrange = 384
#1 in x chance that a spawning storm will spawn as a squall
# Default: 10
# Range: 1 ~ 100
chanceinonesquall = 10
#1 in x chance that a spawning storm will spawn as a cyclone
# Default: 16
# Range: 1 ~ 100
chanceinonecyclone = 16
#1 in x chance that a storm will progress to stage 1
# Default: 2
# Range: 1 ~ 100
chanceinonestage1 = 2
#1 in x chance that a storm will progress to stage 2
# Default: 3
# Range: 1 ~ 100
chanceinonestage2 = 3
#1 in x chance that a storm will progress to stage 3 / tornado
# Default: 5
# Range: 1 ~ 100
chanceinonestage3 = 5
#Risk curve, higher is rarer
# Default: 1.0
# Range: 0.5 ~ 2.0
riskcurve = 1.0
#Multiplier of squall windspeeds
# Default: 1.25
# Range: 0.0 ~ 2.0
squallstrengthmultiplier = 1.25
#Chance a storm will spawn each minute
# Default: 0.2
# Range: 0.0 ~ 1.0
stormspawnchanceperminute = 0.2
#Whether chance to spawn storms and chance for storms to progress is affected by the game environment
environmentsystem = true
#Maximum number of active storms allowed to spawn
# Default: 5
# Range: 1 ~ 10
maxstorms = 5
#Maximum precipitation accumulation, 0 = off
# Default: 6
# Range: 0 ~ 8
snowaccumulationheight = 6
#List of blocks and respective windspeed at which they get damaged
blockstrengths = ["minecraft:acacia_leaves=55","minecraft:azalea_leaves=55","minecraft:birch_leaves=50","minecraft:dark_oak_leaves=55","minecraft:cherry_leaves=55","minecraft:flowering_azalea_leaves=55","minecraft:mangrove_leaves=65","minecraft:oak_leaves=55","minecraft:jungle_leaves=55","minecraft:chain=75","minecraft:lantern=75","minecraft:soul_lantern=75","minecraft:white_wool=60","minecraft:orange_wool=60","minecraft:magenta_wool=60","minecraft:light_blue_wool=60","minecraft:yellow_wool=60","minecraft:lime_wool=60","minecraft:pink_wool=60","minecraft:gray_wool=60","minecraft:light_gray_wool=60","minecraft:cyan_wool=60","minecraft:purple_wool=60","minecraft:blue_wool=60","minecraft:brown_wool=60","minecraft:green_wool=60","minecraft:red_wool=60","minecraft:black_wool=60","minecraft:base_stone_overworld=325","minecraft:gravel=225","minecraft:sand=225","minecraft:red_sand=225","minecraft:dirt=250","minecraft:grass_block=250","minecraft:podzol=250","minecraft:mycelium=250","minecraft:coarse_dirt=250","minecraft:rooted_dirt=250","minecraft:farmland=250","minecraft:dirt_path=250","minecraft:terracotta=250","minecraft:white_terracotta=250","minecraft:orange_terracotta=250","minecraft:magenta_terracotta=250","minecraft:light_blue_terracotta=250","minecraft:yellow_terracotta=250","minecraft:lime_terracotta=250","minecraft:pink_terracotta=250","minecraft:gray_terracotta=250","minecraft:light_gray_terracotta=250","minecraft:cyan_terracotta=250","minecraft:purple_terracotta=250","minecraft:blue_terracotta=250","minecraft:brown_terracotta=250","minecraft:green_terracotta=250","minecraft:red_terracotta=250","minecraft:black_terracotta=250","minecraft:white_glazed_terracotta=250","minecraft:orange_glazed_terracotta=250","minecraft:magenta_glazed_terracotta=250","minecraft:light_blue_glazed_terracotta=250","minecraft:yellow_glazed_terracotta=250","minecraft:lime_glazed_terracotta=250","minecraft:pink_glazed_terracotta=250","minecraft:gray_glazed_terracotta=250","minecraft:light_gray_glazed_terracotta=250","minecraft:cyan_glazed_terracotta=250","minecraft:purple_glazed_terracotta=250","minecraft:blue_glazed_terracotta=250","minecraft:brown_glazed_terracotta=250","minecraft:green_glazed_terracotta=250","minecraft:red_glazed_terracotta=250","minecraft:black_glazed_terracotta=250","minecraft:stone=325","minecraft:granite=325","minecraft:polished_granite=325","minecraft:diorite=325","minecraft:polished_diorite=325","minecraft:andesite=325","minecraft:polished_andesite=325","minecraft:tuff=325","minecraft:deepslate=325","minecraft:polished_deepslate=325","minecraft:cobblestone=325","minecraft:stone_bricks=325","minecraft:mossy_stone_bricks=325","minecraft:cracked_stone_bricks=325","minecraft:chiseled_stone_bricks=325","minecraft:stone_brick_stairs=325","minecraft:stone_brick_slab=325","minecraft:cobblestone_stairs=325","minecraft:cobblestone_slab=325","minecraft:infested_stone=325","minecraft:infested_cobblestone=325","minecraft:infested_stone_bricks=325","minecraft:deepslate_bricks=325","minecraft:deepslate_tiles=325","minecraft:polished_deepslate_stairs=325","minecraft:polished_deepslate_slab=325","minecraft:cobbled_deepslate=325","minecraft:cobbled_deepslate_stairs=325","minecraft:cobbled_deepslate_slab=325","minecraft:deepslate_brick_stairs=325","minecraft:deepslate_brick_slab=325","minecraft:deepslate_tile_stairs=325","minecraft:deepslate_tile_slab=325","minecraft:smooth_stone=325","minecraft:smooth_stone_slab=325","minecraft:chiseled_deepslate=325","minecraft:calcite=325"]
#List of blocks not allowed to be damaged
blacklistedblocks = []
#List of blocktags not allowed to be damaged
blacklistedblocktags = ["minecraft:ice"]
#List of valid dimensions for spawning weather
validdimensions = ["minecraft:overworld"]
#Size of storms
# Default: 300.0
# Range: 128.0 ~ 512.0
stormsize = 300.0
#Overcast Modifier
# Default: 0.85
# Range: 0.0 ~ 0.8999999761581421
overcastpercent = 0.85
#Rain Modifier
# Default: 0.8
# Range: 0.0 ~ 1.25
rainstrength = 0.8
#Height of first cloud layer
# Default: 315.0
# Range: 150.0 ~ 350.0
layer0height = 315.0
#Height of cirrus cloud layer
# Default: 2000.0
# Range: 1000.0 ~ 3000.0
layerCheight = 2000.0
#Maximum width of tornadoes
# Default: 225
# Range: 100 ~ 800
maxtornadowidth = 225
#Whether storms will aim at the player whenever strengthening into a tornado
aimatplayer = true
#Random range of blocks that storms will aim at around players
# Default: 248.0
# Range: 0.0 ~ 1024.0
aimatplayeroffset = 248.0
#Maximum number of blocks allowed to be damaged by a tornado per tick
# Default: 12500
# Range: 5000 ~ 40000
maxblocksdamagedpertick = 12500
#Whether damage should run every tick (off) or every 5th tick (on)
damageevery5thtick = true
#Whether debarking will be applied to logs
dodebarking = true
